name:  Deploy

on:
  push:
    branches: [ main, test ]

jobs:

  deploy-testing:
    name: Deploy to testing
    environment:
      name: Testing
    if: github.event.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to testing using ${{ secrets.mysecret }}
        
  deploy-staging:
    name: Deploy to staging
    environment:
      name: Staging
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to staging using ${{ secrets.mysecret }}
        
  deploy-production:
    name: Deploy to production
    environment:
      name: Production
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to production using ${{ secrets.PROD }}
